### ISSUE TITLE
SVN errorcode=2 Could not open the requested SVN filesystem

### ISSUE THREAD

**Issue by btlaw** [erik-wramner/docker-httpd-svn#1]
Hello
I use the following docker-compose to run docker-httpd-svn,
```text
image: docker-httpd-svn
ports:
  - "443:443"
volumes:
  - /volume1/svn-repos:/svn
  - /var/services/homes/docker/config/localcerts:/etc/ssl/localcerts:ro
environment:
  - HTTPD_SSL=on
  - HTTPD_SERVER_NAME=www.mydomain.com
```
Access the URL: https://www.mydomain.com/svn/repos/myrepo in my browser,
I get the error:
```html
<D:error xmlns:D="DAV:" xmlns:m="http://apache.org/dav/xmlns" xmlns:C="svn:">
<C:error/>
<m:human-readable errcode="2"> Could not find the requested SVN filesystem </m:human-readable>
</D:error>
```
`chown -R httpd:httpd /svn/repos/myrepo`  has been executed.
I use Google a day to search the solution, but no solution is found.
Would you help me to fix it?

**Comment by erik-wramner** [comment]
I think the problem is that you are mounting a file system folder (`/volume1/svn-repos`). There is nothing wrong with that, but it can be tricky to get permissions right and on some platforms there may be other problems as well (SELinux). The quick fix would be to use a docker volume instead. That is what I am doing. Then docker will take care of the permissions (and initial content!) so that they are in line with what the container expects when the volume is created.

If you absolutely want to mount a folder you need to ensure that the expected content is there and has the right permissions (from Dockerfile):
```
RUN groupadd -r httpd && useradd -r -g httpd httpd \
    && mkdir -p /svn/repos \
    && mkdir -p /svn/config \
    && mkdir -p /svn/backup \
    && chown -R httpd:httpd /svn/repos
COPY conf/* /svn/config/
```

Note that the httpd user is the httpd user in the container, not on the host! They may have different numeric user ids.

Good luck!

**Comment by btlaw** [comment]
Thank you so much for your reply.
I will try it.

**Comment by btlaw** [comment]
I don't mount a folder of svn repos to run docker-httpd-svn,
```text
image: docker-httpd-svn
ports:
  - "443:443"
volumes:
  - /var/services/homes/docker/config/localcerts:/etc/ssl/localcerts:ro
environment:
  - HTTPD_SSL=on
  - HTTPD_SERVER_NAME=www.mydomain.com
```
and then in the container I create svn user and repository:/svn/repos/myrepo.
Access the URL: https://www.mydomain.com/svn/repos/myrepo, I get the same error.
In this case I think there should be no permissions problem.
Do you know the reason?

**Comment by erik-wramner** [comment]
Well, have you created the repository? You don't write anything about that, just about chown.

You can either set SVN_REPO_NAME=myrepo, SVN_USER=admin, SVN_PASSWORD=securepassword (with suitable values for the user and password) and let the container create an empty repository for you as well as a user, or you can do it manually, see the docs.

As a quick test I would suggest setting the properties. If that helps perhaps you can do the same thing with the folder mount and see if this was the problem all along. You can then adjust things to your liking.

**Comment by btlaw** [comment]
Yes, I have used  docker-compose and done it manually to create the repository.
But I get the same error by both methods.
Docker-compose:
```text
image: docker-httpd-svn
ports:
  - "443:443"
volumes:
  - /var/services/homes/docker/config/localcerts:/etc/ssl/localcerts:ro
environment:
  - HTTPD_SSL=on
  - HTTPD_SERVER_NAME=www.mydomain.com
  - SVN_REPO_NAME=proj
  - SVN_USER=myuser
  - SVN_PASSWORD=mypassword
```
Shell command:
```bash
docker exec -it fac2e371b591 /bin/bash
htpasswd -cB /svn/config/svn-users myuser
svnadmin create /svn/repos/proj
chown -R httpd:httpd /svn/repos/proj
```

**Comment by erik-wramner** [comment]
Ah, I think I may have found it. You're using https://www.mydomain.com/svn/repos/myrepo (or proj in the recent example?) but it should be https://www.mydomain.com/svn/myrepo without the repos part. Try that. If it doesn't work, please post the output of `docker-compose logs`.

**Comment by btlaw** [comment]
It's worked. Thanks mate!
